# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a71c83e5983d35d12b6b26d2a98985a1c035820c0a2f0e0ba9103aaf83ec7843327aa5564ca2e6d066a713e6cfa2f5fd0924364437ce506530c7c58aa4f0711

test:
  secret_key_base: c06ba5651e674d402fe3283a70cc3d4c06ab36addc1643f22575c9de70da7ef8c263864b43ec96d766dafd232016cd43a68087b34eaae69a37eee74ca1175ade

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
